<a href="https://colab.research.google.com/github/agarwalarpit99/Python-code-snippets/blob/master/Numpy_Dec_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
arr=[1,2,3,4,5]
arr_np=np.array(arr)

In [ ]:
print(arr_np)

[1 2 3 4 5]


In [ ]:
arr_np

array([1, 2, 3, 4, 5])

In [ ]:
arr_np.shape

(5,)

In [ ]:
arr=arr_np

In [ ]:
arr_np.reshape(1,5)
arr_np

array([1, 2, 3, 4, 5])

In [ ]:
#Multidemiaal array
arr1=[1,2,3,4,5]
arr2=[6,7,8,9,10]
arr3=[11,12,13,14,15]
arry=np.array([arr1,arr2,arr3])
arry

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
arry.shape

(3, 5)

In [ ]:
arry.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

Indexing in Numpy


In [ ]:
arr=np.array([11,12,13,14,15,16,17,18])


In [ ]:
arr[4]

15

In [ ]:
#Multidemiaal array
arr1=[1,2,3,4,5]
arr2=[6,7,8,9,10]
arr3=[11,12,13,14,15]
arr=np.array([arr1,arr2,arr3])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
arr[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
# 2 3
# 7 8

arr[0:2,]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [ ]:
'''9 10
  14 15'''
arr[1:,3:]

array([[ 9, 10],
       [14, 15]])

In [ ]:
#arange

arr=np.arange(0,10,step=2)
arr

array([0, 2, 4, 6, 8])

In [ ]:
#linspace
arr=np.linspace(0,10,50)


In [ ]:
arr

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
# Broadcasting

arr[3:]=100

In [ ]:
arr

array([  0.        ,   0.20408163,   0.40816327, 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        ])

In [ ]:
arr=np.arange(0,10,1)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1=arr
arr1[3:]=65
arr1

array([ 0,  1,  2, 65, 65, 65, 65, 65, 65, 65])

In [ ]:
arr

array([ 0,  1,  2, 65, 65, 65, 65, 65, 65, 65])

In [ ]:
#Hence noted that array in numpy are reference type

In [ ]:
#copy
arr1=arr.copy()
arr1[3:]=56
arr1

array([ 0,  1,  2, 56, 56, 56, 56, 56, 56, 56])

In [ ]:
arr

array([ 0,  1,  2, 65, 65, 65, 65, 65, 65, 65])

Some numpy cases used in EDA

In [ ]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr<5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [ ]:
arr[arr<5]

array([0, 1, 2, 3, 4])

In [ ]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr=np.arange(0,10).reshape(5,2)


In [ ]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
arr=np.ones(4,dtype=int)
arr

array([1, 1, 1, 1])

In [ ]:
arr=np.ones((2,5),dtype=float)
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.random.rand(2,5)

array([[0.85352486, 0.47427814, 0.09940458, 0.07724715, 0.84438493],
       [0.73205373, 0.86719622, 0.85647257, 0.61858131, 0.59383418]])

In [ ]:
np.random.randn(2,5) #It is standad normal distribution

array([[ 0.611723  ,  0.54253436, -0.03771769,  1.61121878, -1.31898818],
       [ 0.13632723, -1.16090644, -0.89457486,  0.80274988,  0.83049859]])

In [ ]:
np.random.randint(0,100,8)

array([35, 41, 98, 32, 63, 57, 79, 45])

In [ ]:
np.random.sample((2,5)) #return random float values betwwnn 0.0 to 1.0

array([[0.40226453, 0.68322944, 0.27999043, 0.71168397, 0.53825852],
       [0.03764403, 0.0595707 , 0.45095551, 0.95616876, 0.09864263]])